<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SQLMode_ExecuteStoredProcedureWithData" Id="{c777563f-9014-41c4-bf39-48d4168c3597}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SQLMode_ExecuteStoredProcedureWithData
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>