<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PLC_Mode" Id="{97bd568f-b367-4734-9215-468bdf0bc17d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PLC_Mode
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_CreateDatabasePlcMode();

PRG_CreateTablePlcMode();

PRG_DeleteRowDatabasePlcMode();

PRG_WriteDatabasePlcMode();

PRG_ReadDatabasePlcMode();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>