<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SQL_Mode" Id="{9b9ec1e5-89f5-4b32-9375-a59a82ba09f2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SQL_Mode
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_CreateTableSqlMode();

PRG_DeleteRowSqlMode();

PRG_ReadDatabaseSqlMode();

PRG_WriteDatabaseSqlMode();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>